version: '3'
networks:
  nginx-php-mysql:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    networks:
      - nginx-php-mysql
  php:
    container_name: php-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - nginx-php-mysql
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0375Ihor_
      MYSQL_PASSWORD: Devbase75_
      MYSQL_USER: dev
      MYSQL_DATABASE: BookAPI
    ports:
      - "33306:3306"
    restart: always
    networks:
      - nginx-php-mysql
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/nginx/books-api
    working_dir: /var/www/nginx/books-api